name: AdvancedAdminTools
version: '1.0'
main: fr.caraito.advancedAdminTools.Main
api-version: '1.18'
authors: [ Caraito ]
description: An advanced admin tools plugin


commands:
  ban:
    description: Ban a player from the server.
    permission: aat.ban
  mute:
    description: Mute a player in the chat.
    permission: aat.mute
  warn:
    description: Warn a player.
    permission: aat.warn
  unban:
    description: Unban a player from the server.
    permission: aat.unban
  unmute:
    description: Unmute a player in the chat.
    permission: aat.unmute
  tools:
    description: Open the admin tools menu.
    permission: aat.tools